### ISSUE TITLE
Blocks configuration sync

### ISSUE THREAD

**Issue by a8w4** [backdrop-contrib/shield#2]
This module blocks configuration sync altogether, because it throws an error that its configuration is not known by the system.
I suspect this is because hook_config_info() is not implemented...

**Comment by laryn** [comment]
Thanks, good catch! Can you test the latest changes and see if things are working better? If you can confirm I'll make a new release.

**Comment by a8w4** [comment]
This is a big improvement (sorry for the delay - I was sick for quite a while) - thanks!
Although I was surprised that I had to activate the module manually before it was able to synchronize - but I guess this is a general problem of Backdrop Core...
